export PATH="$PATH":"$HOME/.pub-cache/bin"
# export PATH="$PATH":"$HOME/fvm/default/bin"
export PATH="$PATH":"$(brew --prefix)/bin"
export PATH="$PATH":"/home/linuxbrew/.linuxbrew/bin"
export PATH="$PATH":"/home/linuxbrew/fvm/default/bin"
